### ISSUE TITLE
Service doesn't submit tracks, but manually running `mpris-scrobbler` does (F36, 0.5)

### ISSUE THREAD

**Issue by C-Lunn** [mariusor/mpris-scrobbler#91] opened 2022-05-17 16:24 UTC
Scrobbling from Spotify behind a proxy has been broken for years and Spotify are unwilling to fix it, so this is a lifesaver. 

I don't mind having it run in a tmux session or something, so not the end of the world, but I'm confused as to why the service doesn't work. My only thought is it's something to do with the proxy but I don't really know how to drill into that -- http(s)_proxy is set for both my user and root, and in GNOME config.

Output of `systemctl --user status mpris-scrobbler.service` (last.fm does not receive anything):
```
 ~/l/mpris-scrobbler    systemctl --user status mpris-scrobbler.service                                                                                                                 16.3s  Tue 17 May 2022 17:08:08 BST
● mpris-scrobbler.service - daemon to scrobble tracks loaded from the MPRIS DBus interface to compatible services
     Loaded: loaded (/usr/lib/systemd/user/mpris-scrobbler.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2022-05-17 17:06:36 BST; 1min 43s ago
       Docs: man:mpris-scrobbler
   Main PID: 34790 (mpris-scrobbler)
      Tasks: 1 (limit: 38369)
     Memory: 2.7M
        CPU: 12ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/mpris-scrobbler.service
             └─34790 /usr/bin/mpris-scrobbler -vv

May 17 17:08:14 rd015816 mpris-scrobbler[34790]: DEBUG   changed::volume:               no
May 17 17:08:14 rd015816 mpris-scrobbler[34790]: DEBUG   changed::position:            yes
May 17 17:08:14 rd015816 mpris-scrobbler[34790]: DEBUG   changed::playback_status:      no
May 17 17:08:14 rd015816 mpris-scrobbler[34790]: DEBUG   changed::track:               yes
May 17 17:08:14 rd015816 mpris-scrobbler[34790]: DEBUG   events::add_event:now_playing[Spotify] in 0.000s, ellapsed 0.000s
May 17 17:08:14 rd015816 mpris-scrobbler[34790]: DEBUG   events::add_event:queue[Spotify] in 131.000 seconds
May 17 17:08:14 rd015816 mpris-scrobbler[34790]: DEBUG   events::triggered(0x7ffc819c8a90:0x7ffc819c8a98):now_playing
May 17 17:08:14 rd015816 mpris-scrobbler[34790]: INFO    scrobbler::now_playing[Spotify]: True Lovers//Holy Holy//Paint
May 17 17:08:14 rd015816 mpris-scrobbler[34790]: WARNING curl::multi_timer_activation:failed: API function called from within callback
May 17 17:08:14 rd015816 mpris-scrobbler[34790]: DEBUG   events::add_event:now_playing[Spotify] in 65.000s, ellapsed 0.000s
```

Result of starting the scrobbler manually:
```
~/l/mpris-scrobbler    mpris-scrobbler -v                                                                                                                                                      Tue 17 May 2022 17:08:20 BST
INFO    scrobbler::now_playing[Spotify]: True Lovers//Holy Holy//Paint
INFO     api::submitted_to[last.fm]: ok
^[[A^[[BINFO    scrobbler::now_playing[Spotify]: True Lovers//Holy Holy//Paint
INFO     api::submitted_to[last.fm]: ok
INFO    scrobbler::scrobble:(   0) True Lovers//Holy Holy//Paint
INFO     api::submitted_to[last.fm]: ok
INFO    scrobbler::now_playing[Spotify]: True Lovers//Holy Holy//Paint
INFO     api::submitted_to[last.fm]: ok
```

I feel like this is highly likely to be user error, but I can't for the life of me figure out what I've done wrong.
Any help would be appreciated, thanks.

**Comment by gbcox** [comment] 2022-05-17 16:51
If your using Fedora 36 mpris-scrobbler is broken.  See my problem reports.

**Comment by C-Lunn** [comment] 2022-05-17 16:56
> If your using Fedora 36 mpris-scrobbler is broken. See my problem reports.

I don't appear to be experiencing the same error as yourself -- thanks for putting those compile flags in, else I'd never have figured it out. Scrobbling (at least via Spotify to last.fm) works fine for me, but only if I run the scrobbler manually. Perhaps also start it manually and see if you experience the same?

**Comment by gbcox** [comment] 2022-05-17 17:46
Well, that's bizarre.  You're correct, scrobbling works when started manually instead of using the service.  I did notice an issue however if I start mpris-scobbler first and then start elisa, I get this:
mpris-scrobbler -vvvvvv
DEBUG   main::loading_credentials: ok
DEBUG   main::loading_config: ok
ERROR     mpris::failed_to_load_player_name: This message iterator must have variant type
INFO    mpris_player::opened[1]: org.mpris.MediaPlayer2.elisa:1.14989
WARNING mpris_player::unable to load properties from message

If I open elisa first then mpris-scrobbler it works.  I'll look around and see if I can find any reports on issues with systemd.

**Comment by gbcox** [comment] 2022-05-17 18:20
Try commenting out CPUQuota and see if that does anything for you.

**Comment by C-Lunn** [comment] 2022-05-18 09:58
> Try commenting out CPUQuota in mpris-scrobbler.service and see if that does anything for you.

Commenting out results in the following:
```
May 18 10:54:03 rd015816 mpris-scrobbler[4550]: DEBUG   events::add_event:queue[Spotify] in 15.00s
May 18 10:54:03 rd015816 mpris-scrobbler[4550]: INFO    scrobbler::now_playing[Spotify]: Yanada//The Preatures//Girlhood
May 18 10:54:03 rd015816 mpris-scrobbler[4550]: DEBUG   events::add_event:now_playing[Spotify] in 65.00s, elapsed 145.00s
May 18 10:54:06 rd015816 mpris-scrobbler[4550]: WARNING curl::transfer::done[0]: https://ws.audioscrobbler.com/2.0/?format=json => (28) Failed to connect to ws.audioscrobbler.com port 443 after 2703 ms: Connection timed out
May 18 10:54:06 rd015816 mpris-scrobbler[4550]: INFO     api::submitted_to[last.fm]: nok
May 18 10:54:06 rd015816 mpris-scrobbler[4550]: DEBUG   curl::retrying[1]: in 3.00s
```
And continues timing out.  To confirm, it still works if I run it manually.
I'm thinking now this has something to do with proxy, but changing `-vv` to `-vvvv` in the .service didn't seem to reflect the changes even after a `systemctl daemon-reload`.  Any ideas? Thanks.

I'll try listenbrainz at some point in the future, but given that you can reproduce it, I feel it's not the platform that is at fault.

Thanks for the help.

**Comment by gbcox** [comment] 2022-05-18 14:20
Yeah, we need Marius to weigh in and assist. I'll post an alternate workaround in the Fedora bug:  https://bugzilla.redhat.com/show_bug.cgi?id=2075372

**Comment by mariusor** [comment] 2022-06-09 21:05
Hi guys, sorry for the long time it took me to notice the issue. :)

@C-Lunn it's possible that you're right and the problem is that the systemd service doesn't propagate the PROXY environment variables from your session to the systemd user session. 

Check if using [PassEnvironment](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PassEnvironment=) to pass them works for you. If it does I would appreciate a PR with the changes. :)

**Comment by gbcox** [comment] 2022-06-09 22:29
I'm testing now with the curl patch, which seems to have fixed the issue.  Will advise.

**Comment by gbcox** [comment] 2022-06-10 03:15
New build is on koji and should be pushed to the testing repository shortly:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1980391

**Comment by jeff-mclean** [comment] 2022-08-15 07:00
Hi,

I really love this scrobbler service - I moved from Rhythmbox to Quodlibet only a few days ago.

I like to scrobble with both librefm and lastfm, so this is a boon.

But I can confirm I'm having the issue of scrobbling not working when started as a service, as well as only doing the "Now Playing thing  and not confirming the play (on both Lastfm and Librefm.)

I'm on Mint 21 (ubuntu 22.04 base)

I compiled from version 0.5.0; did that include the curl patch referenced above, and if so, was that meant to fix both issues outlined above?

Any help you can give would be awesome.

Cheers,
Jeff

**Comment by mariusor** [comment] 2022-08-15 15:14
Hi @jeff-mclean, have you tried the change I proposed in [this comment](https://github.com/mariusor/mpris-scrobbler/issues/91#issuecomment-1151624153)? It's possible that the environment in the systemd user slice is different than the one you have in your TTY. Check for differences and see what fixes it.

**Comment by jeff-mclean** [comment] 2022-08-17 00:48
Hi @mariusor,

Your fix did indeed work!  For others following on (that might be a little unsure of exactly how to enact the fix in your comment) in a terminal, I issued
`systemctl --user stop mpris-scrobbler.service`
`sudo vi /usr/local/lib/systemd/user/mpris-scrobbler.service`
- Added PassEnvironment = PROXY to the [Service] section
`systemctl --user daemon-reload`
`systemctl --user start mpris-scrobbler.service`

Everything works like a charm!

Thanks for your brilliance.

Cheers.

**Comment by mariusor** [comment] 2022-08-18 09:59
@jeff-mclean would you consider opening a PR with this change? I think it would help other people. :)

**Comment by jeff-mclean** [comment] 2022-08-18 22:01
oh Gawd, I don't know how to do that.  I just looked up PR and saw that it meant pull request and have never done that before.  i'll give it a go.  you mean a pull request for that line of code in the service file, right?

so sorry if i'm a dill and have wandered far off the range here...

**Comment by mariusor** [comment] 2022-08-19 14:07
Merged, thank you @jeff-mclean  :)

I will be releasing a new version soon(ish).

**Closed by mariusor** 2022-08-19 14:07 UTC

**Comment by akyag** [comment] 2022-11-11 06:08
I am having this issue too.
```mpris-scrobbler.service - daemon to scrobble tracks loaded from the MPRIS DBus interface to compatible services
     Loaded: loaded (/usr/lib/systemd/user/mpris-scrobbler.service; enabled; preset: enabled)
     Active: active (running) since Fri 2022-11-11 11:34:42 IST; 48s ago
       Docs: man:mpris-scrobbler
   Main PID: 146762 (mpris-scrobbler)
      Tasks: 1 (limit: 17898)
     Memory: 6.8M
        CPU: 460ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/mpris-scrobbler.service
             └─146762 /usr/bin/mpris-scrobbler -vv

Nov 11 11:35:12 quady mpris-scrobbler[146762]: DEBUG   curl::retrying[4]: in 6.00s
Nov 11 11:35:19 quady mpris-scrobbler[146762]: WARNING curl::transfer::done[1]: https://ws.audioscrobbler.com/2.0/?format=json => (>
Nov 11 11:35:19 quady mpris-scrobbler[146762]: INFO     api::submitted_to[last.fm]: nok
Nov 11 11:35:19 quady mpris-scrobbler[146762]: DEBUG   curl::retrying[3]: in 5.00s
Nov 11 11:35:19 quady mpris-scrobbler[146762]: WARNING curl::transfer::done[2]: https://ws.audioscrobbler.com/2.0/?format=json => (>
Nov 11 11:35:19 quady mpris-scrobbler[146762]: INFO     api::submitted_to[last.fm]: nok
Nov 11 11:35:19 quady mpris-scrobbler[146762]: DEBUG   curl::retrying[1]: in 3.00s
Nov 11 11:35:19 quady mpris-scrobbler[146762]: WARNING curl::transfer::done[0]: https://ws.audioscrobbler.com/2.0/?format=json => (>
Nov 11 11:35:19 quady mpris-scrobbler[146762]: INFO     api::submitted_to[last.fm]: nok
Nov 11 11:35:19 quady mpris-scrobbler[146762]: DEBUG   curl::retrying[5]: in 7.00s```

but works in terminal 
```~ mpris-scrobbler -vv                            
DEBUG   main::loading_credentials: ok
DEBUG   main::loading_config: ok
DEBUG   events::add_event:now_playing[Quod Libet] in 0.00s, elapsed 4.00s
DEBUG   events::add_event:queue[Quod Libet] in 145.00s
INFO    scrobbler::now_playing[Quod Libet]: Africa//Toto//Toto IV
DEBUG   events::add_event:now_playing[Quod Libet] in 65.00s, elapsed 4.00s
INFO     api::submitted_to[last.fm]: ok```

adding` PassEnvironment = PROXY` didn't do anything.

**Comment by mariusor** [comment] 2022-11-11 11:50
You need to check the differences in environment between your regular terminal shell and the environment that the systemd user session runs under:

```sh
$ env
$ systemctl --user show-environment
# or if you want to diff directly:
$ diff --unified <(env | sort) <(systemctl --user show-environment | sort)
```

Then you check what might be related to connectivity and is different between the two.

**Comment by akyag** [comment] 2022-11-12 06:46
Couldn't really figure that out. Tried setting the environment etc but no luck yet.

**Comment by mariusor** [comment] 2022-11-12 14:34
Could you post here the output of the first two commands from my previous message? Maybe we can figure it out together.

**Comment by akyag** [comment] 2022-11-12 16:54
env 
```
BROWSER=firefox
EDITOR=
HOME=/home/akya
LANG=en_IN
LC_ADDRESS=en_IN
LC_IDENTIFICATION=en_IN
LC_MEASUREMENT=en_IN
LC_MONETARY=en_IN
LC_NAME=en_IN
LC_NUMERIC=en_IN
LC_PAPER=en_IN
LC_TELEPHONE=en_IN
LC_TIME=en_IN
LOGNAME=akya
MAIL=/var/spool/mail/akya
PATH=/home/akya/.local/share/pnpm:/home/akya/gems/bin:/home/akya/.npm-global/bin:/home/akya/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/akya/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/akya/.rvm/bin
SHELL=/usr/bin/zsh
SYSTEMD_EXEC_PID=977
USER=akya
XDG_RUNTIME_DIR=/run/user/1000
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_SESSION=plasma
DISPLAY=:0
DOTNET_BUNDLE_EXTRACT_BASE_DIR=/home/akya/.cache/dotnet_bundle_extract
DOTNET_ROOT=/usr/share/dotnet
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/akya/.gtkrc-2.0:/home/akya/.config/gtkrc-2.0
GTK3_MODULES=xapp-gtk3-module
GTK_MODULES=canberra-gtk-module
GTK_RC_FILES=/etc/gtk/gtkrc:/home/akya/.gtkrc:/home/akya/.config/gtkrc
KDE_APPLICATIONS_AS_SCOPE=1
KDE_FULL_SESSION=true
KDE_SESSION_UID=1000
KDE_SESSION_VERSION=5
MOTD_SHOWN=pam
OLDPWD=/home/akya
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
PWD=/home/akya
QT_AUTO_SCREEN_SCALE_FACTOR=0
SESSION_MANAGER=local/quady:@/tmp/.ICE-unix/919,unix/quady:/tmp/.ICE-unix/919
SHLVL=1
XAUTHORITY=/home/akya/.Xauthority
XCURSOR_SIZE=24
XCURSOR_THEME=Qogir
XDG_CONFIG_DIRS=/home/akya/.config/kdedefaults:/etc/xdg
XDG_CURRENT_DESKTOP=KDE
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=KDE
XDG_SESSION_ID=2
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
XDG_SESSION_TYPE=x11
XDG_VTNR=1
_=/usr/bin/env
MANAGERPID=861
INVOCATION_ID=1ac4cdc389164cf39239ad4acfefadb4
JOURNAL_STREAM=8:20318
DESKTOP_STARTUP_ID=quady;1668271682;608231;977_TIME52784694
KITTY_WINDOW_ID=1
WINDOWID=157286414
TERM=xterm-kitty
COLORTERM=truecolor
KITTY_PID=445456
KITTY_PUBLIC_KEY=1:IAXvxd2+Qb_ZuZ<L$Ks^_Y&$q8$n!B$(K<49Nw`?
TERMINFO=/usr/lib/kitty/terminfo
KITTY_INSTALLATION_DIR=/usr/lib/kitty
PAGER=less
GREP_COLOR=37;45
GREP_COLORS=mt=37;45
LESS_TERMCAP_mb=[1;31m
LESS_TERMCAP_md=[1;31m
LESS_TERMCAP_me=[0m
LESS_TERMCAP_se=[27m
LESS_TERMCAP_so=[7m
LESS_TERMCAP_ue=[0m
LESS_TERMCAP_us=[1;32m
LS_COLORS=di=1;34:ln=35:so=32:pi=33:ex=31:bd=1;36:cd=1;33:su=30;41:sg=30;46:tw=30;42:ow=30;43
EXA_COLORS=da=1;34:gm=1;34
BORG_PASSCOMMAND=cat /home/akya/.borg-passphrase
VISUAL=micro
PNPM_HOME=/home/akya/.local/share/pnpm
HISTFILE=/home/akya/.zhistory
MCFLY_SESSION_ID=W0NYvieGev8qFiSK9u2WHmqV
MCFLY_HISTORY=/tmp/mcfly.kHUAm3od
MCFLY_HISTORY_FORMAT=zsh
```
systemctl --user show-environment
```
BROWSER=firefox
EDITOR=nano
HOME=/home/akya
LANG=en_IN
LC_ADDRESS=en_IN
LC_IDENTIFICATION=en_IN
LC_MEASUREMENT=en_IN
LC_MONETARY=en_IN
LC_NAME=en_IN
LC_NUMERIC=en_IN
LC_PAPER=en_IN
LC_TELEPHONE=en_IN
LC_TIME=en_IN
LOGNAME=akya
MAIL=/var/spool/mail/akya
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/home/akya/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
SHELL=/usr/bin/zsh
SYSTEMD_EXEC_PID=861
USER=akya
XDG_RUNTIME_DIR=/run/user/1000
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_SESSION=plasma
DISPLAY=:0
DOTNET_BUNDLE_EXTRACT_BASE_DIR=/home/akya/.cache/dotnet_bundle_extract
DOTNET_ROOT=/usr/share/dotnet
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/akya/.gtkrc-2.0:/home/akya/.config/gtkrc-2.0
GTK3_MODULES=xapp-gtk3-module
GTK_MODULES=canberra-gtk-module
GTK_RC_FILES=/etc/gtk/gtkrc:/home/akya/.gtkrc:/home/akya/.config/gtkrc
KDE_APPLICATIONS_AS_SCOPE=1
KDE_FULL_SESSION=true
KDE_SESSION_UID=1000
KDE_SESSION_VERSION=5
MOTD_SHOWN=pam
OLDPWD=/home/akya
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
PWD=/home/akya
QT_AUTO_SCREEN_SCALE_FACTOR=0
SESSION_MANAGER=local/quady:@/tmp/.ICE-unix/919,unix/quady:/tmp/.ICE-unix/919
SHLVL=0
XAUTHORITY=/home/akya/.Xauthority
XCURSOR_SIZE=24
XCURSOR_THEME=Qogir
XDG_CONFIG_DIRS=/home/akya/.config/kdedefaults:/etc/xdg
XDG_CURRENT_DESKTOP=KDE
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=KDE
XDG_SESSION_ID=2
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
XDG_SESSION_TYPE=x11
XDG_VTNR=1
_=/usr/bin/startplasma-x11
```

**Comment by mariusor** [comment] 2022-11-13 07:36
I can't see anything that would help, sorry. 

I am not sure what is happening. Since your terminal is not using a PROXY I suspect that the problem is elsewhere, and not related to this particular issue.

If you manage to find a solution, please come back and let us know. :)
