### ISSUE TITLE
Each subsequent track scrobbles over the previous

### ISSUE THREAD

**Issue by alecvn** [mariusor/mpris-scrobbler#64] opened 2019-08-05 23:47 UTC
I've been struggling for a few weeks with this and have been trying different things and checking new releases to eliminate other problems I've been seeing, but now I'm stuck again.  The service mpris-scrobbler doesn't scrobble for me at all, and when I run it manually it scrobbles tracks while they're playing but then erases them just as the next one starts and then scrobbles that track, only to have it overwritten as well when the following track starts.  I keep an eye on last.fm constantly as this happens.  Eventually a `Segmentation fault (core dumped)` error exits the process.  

`$ mpris-scrobbler -vvv` gives the following output:
https://pastebin.com/dHjfwUsq

Distribution: Ubuntu 18.04
Media player: MellowPlayer as well as Amarok

**Comment by mariusor** [comment] 2019-08-06 09:27
Thanx for the ticket.

I also have some segfaults issues with versions higher than 0.3.1 up to latest master, playing with Spotify. I'll add MellowPlayer and Amarok to the list of things to check when I start working on that.

I tried already a couple of fixes, but unfortunately nothing seemed to work so far. 

It is also possible that the causes are different, but somehow I don't think so, so I'll report any progress under this issue.

**Comment by alecvn** [comment] 2019-08-06 09:35
I guess I'm describing two issues here, because I'm not able to successfully scrobble tracks before the segfault occurs - which is usually several tracks in.

At home - where I reported this issue - I'm on latest master.  At work I'm on `v0.3.1-6-gd5b189e` (according to the build version.h) and I never get segfaults and scrobbling works - except for that issue where the first track doesn't scrobble which you've subsequently fixed.

**Comment by mariusor** [comment] 2022-04-18 15:41
@alecvn a long time has passed since you had your issues, I had a number of releases since then. 

If you can reproduce your problem with the last of them, please reopen this ticket or submit a new one, until then I'll close it.

**Closed by mariusor** 2022-04-18 15:41 UTC
Labels: bug
